# Generated by Django 3.2.4 on 2021-06-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasareceber',
            old_name='classificacaoContasAPagar',
            new_name='classificacaoContasAReceber',
        ),
    ]
