# Generated by Django 3.2.4 on 2021-06-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_rename_classificacaocontasapagar_contasareceber_classificacaocontasareceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasapagar',
            name='classificacaoContasAPagar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meuapp.classificacaocontasapagar'),
        ),
    ]
